name: Release
on:
  release:
    types:
      - published
  workflow_dispatch: {}

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  package:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    name: "Package"
    uses: package.yml@main
